name: 'Ponicode Repository Unit Tester'
description: 'Writes unit tests for all your repository'
inputs: 
  repo_path:
    description: 'Path of repo to generate unit tests for'
    required: true
    default: './'
  auth_token:
    description: 'Ponicode token to use Ponicode API'
    required: true
    default: ''
  write_expectations:
    description: 'Boolean. Enter false to write only the input values and true to write input values + expectations'
    required: true
    default: 'true'
  from_diff:
    description: 'Boolean. Enter true to generate test for changes since last repo or enter false if you want to generate for the whole repo'
    required: false
    default: 'false'
  coverage_json_path:
    description: 'String. Enter the path to your coverage-final.json (Example: coverage/coverage-final.json)'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_path }}
    - ${{ inputs.auth_token }}
    - ${{ inputs.write_expectations}}
    - ${{ inputs.from_diff}}
    - ${{ inputs.coverage_json_path}}
